---
title: "DRAFT::: Home"
---

## How do analysts use programming and software engineering in the UK Public Sector?

*Please note that this is a draft piece of analysis which has not yet undergone full quality assurance. Do not use this research for any purpose until this message is removed.*

### The Coding in Analysis and Research survey (CARS) was collected in October 2020

CARS was developed to better understand how programming and software engineering is used in government analysis and research. Most questions focused on whether analysts use software engineering practices when coding as part of their work. These coding practices are components of Reproducible Analytical Pipelines (RAP). You can find links to further information on RAP at the bottom of this page.

The survey was distributed to government analysts and researchers in the Autumn of 2020. The results presented here summarise the key findings from 1,060 responses from over 60 public sector organisations. 

### Who is this research for?

This research was made with senior analysts and leaders in mind.
It will be useful for the development of strategies for public sector analysis and research.
It will also be useful for analysts and researchers in the public sector who are interested in understanding more about how their professions use programming in their work.
Finally, it will be useful to people outside the public sector who are interested in understanding the tools that are used in the public sector for analysis and research.

### How to use this research

Do:

* Explore the data to gain insights about current coding practices in government analysis and research
* Re-use the outputs if you wish

Avoid:

* Attempting to estimate absolute frequencies - we did not use random sampling
* Inferring differences between groups - these outputs are only intended to be descriptive and inferential tests were not carried out
* Comparing results from different departments

### More information on reproducible analytical pipelines

[Quality assurance for coding in analysis and research](https://best-practice-and-impact.github.io/qa-of-code-guidance/)

[Reproducible Analytical Pipelines (RAP) MVP](https://github.com/best-practice-and-impact/rap_mvp_maturity_guidance/blob/master/Reproducible-Analytical-Pipelines-MVP.md)

[RAP champions network](https://gss.civilservice.gov.uk/about-us/champion-networks/reproducible-analytical-pipeline-rap-champions/)

### Contact details

We would like to know what you think of the survey and the outputs. Please contact us if you have feedback on any of the following:

* Outputs/analyses you would like to see added to this research
* Information you would like to see collected in the next iteration of CARS
* Any other comments

If you are interested in this survey or any of the questions asked please contact goodpracticeteam@statistics.gov.uk

If you have any queries or feedback related specifically to this site, then please contact daniel.shiloh@ons.gov.uk