---
title: "Home"
---

## Coding in Analysis and Research Survey (CARS) - Wave 2

### Background to CARS

CARS was developed to better understand how coding is used in government analysis and research. Most questions focused on whether analysts use software engineering practices when coding as part of their work. These coding practices are components of Reproducible Analytical Pipelines (RAP). You can find links to further information on RAP at the bottom of this page.

The survey was distributed to government analysts and researchers in the Autumn of 2020. The results presented here summarise the key findings from 1,060 responses from over 60 government organisations. 

### How to use this dashboard

Do:

* Explore the data to gain insights about current coding practices in government analysis and research
* Re-use the outputs if you wish

Avoid:

* Attempting to estimate absolute frequencies - we did not use random sampling
* Inferring differences between groups - these outputs are only intended to be descriptive and inferential tests were not carried out
* Comparing results from different departments

### More information on reproducible analytical pipelines

[Guide to implementing RAP](https://ukgovdatascience.github.io/rap_companion/)

[RAP champions network](https://gss.civilservice.gov.uk/about-us/champion-networks/reproducible-analytical-pipeline-rap-champions/)

### Contact details

We would like to know what you think of the survey and the outputs. Please contact us if you have feedback on any of the following:

* Outputs/analyses you would like to see added to this dashboard
* Information you would like to see collected in the next iteration of CARS
* Any other comments

If you are interested in this survey or any of the questions asked please contact goodpracticeteam@statistics.gov.uk

If you have any queries or feedback related specifically to this site, then please contact daniel.shiloh@ons.gov.uk